### PR TITLE
Merge fg_specificity_sxw into the phenology scaling branch

### PR DESCRIPTION
**Pull request by chaukap**
fg_specificity_sxw is about ready to merge back into feature_phenology_biomass_scaling.

### CODE REVIEW

**Comment by kpalmqui** [comment]
@chaukap I will test this first thing tomorrow morning and make sure everything looks good.

**Comment by kpalmqui** [comment]
@chaukap the litter Figures generated by compare_files.sh look good,  but I noticed the last Figure for each functional group is labeled "46-53" while all others (biomass, %live) are labeled "46-52".

**Comment by chaukap** [comment]
@kpalmqui I've been running the wrapper for about an hour now and I haven't gotten any log errors. Commit 2463b75 should have resolved the res_avail issue have you pulled the latest commit?

**Comment by kpalmqui** [comment]
@chaukap not sure what happened, as the latest commit was implemented in my testing branch, but you are right - the new columns for BVT were absent from InputData_Rgroup.csv. I've updated the file and am now re-running. Will report back shortly.

**Comment by kpalmqui** [comment]
@chaukap the program completed successfully with no logwarnings on my end.

Once we resolve my other comment above, I will approve the pull request

**Comment by chaukap** [comment]
@kpalmqui da2192e resolves the file naming issue.

**Pull request merged**
