### PR TITLE
Bugfix 127 stepwat2 incompatibility

### PR DESCRIPTION
**Pull request by kpalmqui**
Requesting your review @chaukap on a branch I created that resolves 5 inconsistencies between master of rSFSTEP2 and master of STEPWAT2. This resulted primarily from the recent merge of Fire_testing into STEPWAT2 master.

Please review at your earliest convenience (along with closed issues), as these inconsistencies have rendered master branch of rSFSTEP2 not functional.

### CODE REVIEW

**Comment by chaukap** [comment]
@kpalmqui I have some time to review your changes tomorrow. My initial inspection looks good but I would like to use the office machine to confirm.

**Comment by kpalmqui** [comment]
@chaukap were you able to test on the lab computer with this branch of rSFSTEP2 and feature_space of STEPWAT2?

**Comment by chaukap** [comment]
@kpalmqui I tested with STEPWAT2 master but I can pull feature_space now and make sure.

**Comment by kpalmqui** [comment]
@chaukap sounds good. If you could test with more than just "Current" that would be ideal. Specifically, current conditions and 1 future scenario.

**Comment by chaukap** [comment]
@kpalmqui I just ran with CanESM2 and the results were as expected. Fire return interval was working and sagebrush biomass was between 95 and 90 grams/m^2. Cool forbs had higher biomass than most of the STEPWAT branches I've worked with but this could be due to the sites (1 and 2).

**Comment by kpalmqui** [comment]
@chaukap ok! I will test on my end one more timel before merging into master

**Comment by kpalmqui** [comment]
Additional test runs on Teton failed. Currently trying to identify the problem.

**Comment by kpalmqui** [comment]
@chaukap tested this branch on Teton with both master branch of STEPWAT2 and feature_space branch of STEPWAT2. Both runs completed without problem. 

We can merge this into master now.

**Pull request merged**
